In [2]:
import numpy as np
import pandas as pd
import tensorflow as tf

# EDA에서 했지만 다시 받아온다
train_raw = pd.read_csv('./train2.csv')
test_raw = pd.read_csv('./test2.csv')

train = train_raw.drop(columns = ['id','Unnamed: 0']) # id 제거
test = test_raw.drop(columns = ['id','Unnamed: 0'])

print('===처리 전======================================') # Gender one-hot encoding 처리 전

print(train['Gender'][:3])

print('===처리 후========================================')
from sklearn.preprocessing import OneHotEncoder

train_only_Gender = train[['Gender']]
onehot_encoder = OneHotEncoder()
train_onehot_Gender = onehot_encoder.fit_transform(train_only_Gender)

print(train_onehot_Gender.toarray()[:3])
print(onehot_encoder.categories_)

print('===처리된 train set==================================')

train_noGender = train.drop(('Gender'), axis=1)
train_noGender_np = train_noGender
train = np.c_[train_onehot_Gender.toarray(), train_noGender_np]
print(train[:3])

print('====train set을 y_train과 x_train으로 분리============================')
y_train = np.array(train).T[-1] # Target만 추출한 것: y_data
print(y_train)

x_train = pd.DataFrame(train).drop(10,axis=1) # Target 이외의 데이터: x_data
x_train = np.array(x_train)
print(x_train)

===처리 전======================================
0    M
1    M
2    F
Name: Gender, dtype: object
===처리 후========================================
[[0. 0. 1.]
 [0. 0. 1.]
 [1. 0. 0.]]
[array(['F', 'I', 'M'], dtype=object)]
===처리된 train set==================================
[[ 0.      0.      1.      0.57    0.48    0.18    0.9395  0.399   0.2
   0.295  14.    ]
 [ 0.      0.      1.      0.56    0.425   0.135   0.9415  0.509   0.2015
   0.1975  9.    ]
 [ 1.      0.      0.      0.655   0.51    0.15    1.043   0.4795  0.223
   0.305   9.    ]]
====train set을 y_train과 x_train으로 분리============================
[14.  9.  9. ...  6. 10. 10.]
[[0.     0.     1.     ... 0.399  0.2    0.295 ]
 [0.     0.     1.     ... 0.509  0.2015 0.1975]
 [1.     0.     0.     ... 0.4795 0.223  0.305 ]
 ...
 [0.     1.     0.     ... 0.363  0.1925 0.2515]
 [1.     0.     0.     ... 0.465  0.2055 0.2765]
 [0.     1.     0.     ... 0.7735 0.4405 0.655 ]]


In [20]:
model = tf.keras.models.Sequential([
    tf.keras.layers.Dense(256, activation='relu'),
    tf.keras.layers.Dense(128, activation='relu'),
    tf.keras.layers.Dense(64, activation='relu'),
    tf.keras.layers.Dense(32, activation='relu'),
    tf.keras.layers.Dense(1, activation='relu'), # 확률이나 bool 은 출력노드 1개 - 추천: sigmoid는 0~1 사이 값
])

# 확률 예측에 좋은 loss함수: binary_crossentropy -> 0~1 결과인 분류/확률 문제에서 씀
model.compile(optimizer='adam',loss='mse',metrics=['accuracy'])

In [21]:
#with tf.device("/device:GPU:0"):
model.fit(x_train, y_train, epochs=100)

Epoch 1/100
36/36 [==============================] - 1s 3ms/step - loss: 46.0605 - accuracy: 0.0000e+00
Epoch 2/100
36/36 [==============================] - 0s 3ms/step - loss: 8.7613 - accuracy: 0.0000e+00
Epoch 3/100
36/36 [==============================] - 0s 3ms/step - loss: 7.0763 - accuracy: 0.0000e+00
Epoch 4/100
36/36 [==============================] - 0s 3ms/step - loss: 6.8501 - accuracy: 0.0000e+00
Epoch 5/100
36/36 [==============================] - 0s 3ms/step - loss: 6.7165 - accuracy: 0.0000e+00
Epoch 6/100
36/36 [==============================] - 0s 3ms/step - loss: 6.3849 - accuracy: 0.0000e+00
Epoch 7/100
36/36 [==============================] - 0s 3ms/step - loss: 6.3253 - accuracy: 0.0000e+00
Epoch 8/100
36/36 [==============================] - 0s 3ms/step - loss: 6.0372 - accuracy: 0.0000e+00
Epoch 9/100
36/36 [==============================] - 0s 3ms/step - loss: 5.9566 - accuracy: 0.0000e+00
Epoch 10/100
36/36 [==============================] - 0s 3ms/step - loss

36/36 [==============================] - 0s 3ms/step - loss: 4.9195 - accuracy: 0.0000e+00
Epoch 80/100
36/36 [==============================] - 0s 3ms/step - loss: 4.6319 - accuracy: 0.0000e+00
Epoch 81/100
36/36 [==============================] - 0s 3ms/step - loss: 4.6531 - accuracy: 0.0000e+00
Epoch 82/100
36/36 [==============================] - 0s 3ms/step - loss: 4.6692 - accuracy: 0.0000e+00
Epoch 83/100
36/36 [==============================] - 0s 3ms/step - loss: 4.7108 - accuracy: 0.0000e+00
Epoch 84/100
36/36 [==============================] - 0s 3ms/step - loss: 4.7013 - accuracy: 0.0000e+00
Epoch 85/100
36/36 [==============================] - 0s 3ms/step - loss: 4.9966 - accuracy: 0.0000e+00
Epoch 86/100
36/36 [==============================] - 0s 3ms/step - loss: 4.7987 - accuracy: 0.0000e+00
Epoch 87/100
36/36 [==============================] - 0s 3ms/step - loss: 4.6924 - accuracy: 0.0000e+00
Epoch 88/100
36/36 [==============================] - 0s 3ms/step - loss: 4.7

In [19]:
from keras.models import load_model
model.save('2019076021_김선우.model')

INFO:tensorflow:Assets written to: 2019076021_김선우.model\assets


In [ ]:
# # 4. 모델 학습시키기
# model.fit(x_train, y_train, epochs=5, batch_size=32, validation_data=(x_val, y_val))


In [15]:
from IPython.display import SVG
from keras.utils.vis_utils import model_to_dot

%matplotlib inline

SVG(model_to_dot(model, show_shapes=True).create(prog='dot', format='svg'))

You must install pydot (`pip install pydot`) and install graphviz (see instructions at https://graphviz.gitlab.io/download/) for plot_model/model_to_dot to work.


AttributeError: 'NoneType' object has no attribute 'create'